---
- name: Waiting for instance creation
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensuring port 22 is open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3

- name: Install python3, docker, docker-compose
  hosts: all
  become: yes
  vars_files:
    - docker-vars.yaml
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      # vars:
      #   ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum: 
        name: 
          # - python3
          - docker
          - tree
        update_cache: yes
        state: present

    - name: Install Docker-compose
      ansible.builtin.get_url: 
        # url: https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        url: https://github.com/docker/compose/releases/download/{{compose_version}}/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
      async: 1000
      poll: 0

    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
  
    - name: Install docker python module
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose
    

- name: Add ec2-user to docker group
  hosts: all
  become: yes
  tasks: 
    - name: Add ec2-user to docker group
      ansible.builtin.user: 
        name: ec2-user
        groups: docker
        append: yes

    - name: Reconnect to server session
      ansible.builtin.meta: reset_connection


- name: Start docker containers
  hosts: all
  vars_files:
    - docker-vars.yaml
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: /home/manager/workingWithAnsible/docker-ansible-ec2/ansible.cfg
        dest: /home/ec2-user/ansible_inventory_file.yaml
    
    #If you are using private image, you can use below code block for login
    # - name: Docker login
      # community.docker.docker_login: 
      #   registry_url: https://index.docker.io/v1/
      #   username: {{registry_username}}
      #   password: "{{registry_password}}"

    # - name: Start container from compose
    #   community.docker.docker_compose: 
    #     project_src: /home/ec2-user   